<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Bold.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-BoldItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Italic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Regular.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Black.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BlackItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Bold.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BoldItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Italic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Light.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-LightItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Medium.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-MediumItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Regular.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Thin.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-ThinItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Bold.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-BoldItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Italic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Light.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-LightItalic.ttf" />
    <Content Remove="C:\Users\yahal\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Covers\AboutUs.png" />
    <None Remove="Covers\Flower.png" />
    <None Remove="Covers\Login.png" />
    <None Remove="Covers\Logo.png" />
    <None Remove="Covers\ResetPassPicture.png" />
    <None Remove="Covers\SignOut.png" />
    <None Remove="Fonts\AlexBrush-Regular.ttf" />
    <None Remove="Fonts\RobotoSlab-VariableFont_wght.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Covers\AboutUs.png" />
    <Resource Include="Covers\DefultUser.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Model">
      <HintPath>..\..\Liany34\LitLink_Liany\Service\bin\Debug\net8.0\Model.dll</HintPath>
    </Reference>
    <Reference Include="Service">
      <HintPath>..\..\Liany34\LitLink_Liany\Service\bin\Debug\net8.0\Service.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Covers\Flower.png" />
    <Resource Include="Covers\Login.png" />
    <Resource Include="Covers\Logo.png" />
    <Resource Include="Covers\ResetPassPicture.png" />
    <Resource Include="Covers\SingUp.png" />
    <Resource Include="Covers\SignOut.png" />
    <Resource Include="Fonts\AlexBrush-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RobotoSlab-VariableFont_wght.ttf" />
  </ItemGroup>

</Project>
